Harvey-OS/apex

- include/stdint.h
Change-Id: I72e0ace3c7cc2acb22eddfc05192ec1f6f60b6ee
> Fixing what is needed for GCC.

- lib/ap/amd64/Makefile
- lib/ap/crt/Makefile
- lib/ap/gen/Makefile
- lib/ap/locale/Makefile
- lib/ap/math/Makefile
- lib/ap/multibyte/Makefile
- lib/ap/plan9/Makefile
- lib/ap/posix/Makefile
- lib/ap/stdio/Makefile
- lib/ap/stdlib/Makefile
- lib/ap/string/Makefile
- lib/bsd/Makefile
Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>
> Fix all include files. It builds again. Sort of.

- .travis.yml
- Makefile
- travis.inc
It might even work ...
Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>
> travis: actually test full building.

- cmd/apextest/.gitignore
- cmd/apextest/Makefile
- cmd/apextest/test.c
- lib/9/libc.h
Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>
> Add a test program

- lib/ap/plan9/malloc.c
mksh working
Change-Id: I14aa726f2dd15cafa6e16ccf8d88ac7cf3fe8e09
> Fixing malloc

- include/unistd.h
- lib/ap/internal/sys9.h
- lib/ap/plan9/__sys_close.c
- lib/ap/plan9/__sys_pipe.c
- lib/ap/plan9/_close.c
- lib/ap/plan9/pipe.c
Same way like with other conflict syscalls
Change-Id: Ida74833b796c57317450b541540f3a5473b195fa
> Posixizing pipe syscall through __syscall_pipe

- include/stdio_ext.h
- lib/ap/stdio/_progname.c
- lib/ap/stdio/ext.c
- lib/ap/stdio/ext2.c
Tested with GNU sed 4.2.2
Change-Id: I8e27397377bd4b1da45da7ad6fe51eed7b2d8e94
> Adding stdio_ext

- lib/ap/plan9/_buf.c
- lib/ap/plan9/execve.c
- lib/ap/plan9/mkdir.c
> Fixing execve

- amd64/include/atomic.h
- cmd/expr.c
- include/libgen.h
- include/libintl.h
- lib/ap/bsd/basename.c
- lib/ap/bsd/dirname.c
- lib/ap/locale/dcngettext.c
This is a small step for avoiding libiberty in future.
- expr.c was just forgotten wrongly in previous PR
> Adding gettext and others needed for flex

- include/setjmp.h
- include/stdio.h
Signed-off-by: Keith Poole <keith.poole@gmail.com>
> Increased size of jmp_buf to match actual usage

- include/string.h
- include/termios.h
- lib/ap/string/mempcpy.c
Adding some constants to termios.h
> Adding mempcpy

- cmd/pdksh/Makefile
It works, but rarely. Needs testing.
It isn't into general APEX build, so you need
to run make only for this at this moment.
> Making pdksh working again

- cmd/pdksh/Makefile
- cmd/pdksh/c_ksh.c
- cmd/pdksh/exec.c
- cmd/pdksh/expr.c
- cmd/pdksh/jobs.c
- cmd/pdksh/lex.c
- cmd/pdksh/main.c
- cmd/pdksh/misc.c
- cmd/pdksh/sh.h
- cmd/pdksh/trap.c
- cmd/pdksh/var.c
This won't solve the actual bug
> Fixing pdksh build process

- include/cursor.h
- include/draw.h
- include/event.h
draw for APEX, playing with SDL
> Fixing some guards and headers native related

- lib/ap/amd64/Makefile
- lib/ap/amd64/sigsetjmp.s
- lib/ap/plan9/signal.c
- linux.inc
C version didn't reserve enough registers
> New sigsetjmp for amd64

- Makefile
- cmd/Makefile
- cmd/awk/Makefile
- cmd/troff/Makefile
At top level, "make" will build both the lib and the commands. "make lib"
just builds libap, "make cmd" just builds the commands and copies them
to $ARCH/bin
Signed-off-by: John Floren <john@jfloren.net>
> makefiles for apex, now with commands

- cmd/awk/Makefile
- cmd/troff/Makefile
Signed-off-by: John Floren <john@jfloren.net>
> Use $(LD) instead of $(CC) to link.

- Makefile
- cmd/Makefile
- cmd/README
- cmd/dirname.c
- cmd/kill.c
- cmd/pdksh/Makefile
- cmd/sed/Makefile
Adding rest of single source programs in cmd
> Adding rest of single source programs in cmd

- cmd/uname.c
- include/glob.h
- include/sys/stat.h
- lib/ap/bsd/lstat.c
- lib/ap/plan9/execl.c
- lib/ap/plan9/execlp.c
> Fixing stat.h and glob.h

- lib/ap/plan9/system.c
This replaces #53 now that Harvey has pdksh
It needs a better approachment.
> system() adapted to APEX

- lib/ap/plan9/execle.c
> Fixing last of the execs

- cmd/Makefile
- cmd/compress.c
> Adding compress

- README.md
- cmd/grap/coord.c
- cmd/grap/for.c
- cmd/grap/frame.c
- cmd/grap/grap.h
- cmd/grap/grap.y
- cmd/grap/grapl.lx
- cmd/grap/input.c
- cmd/grap/label.c
- cmd/grap/main.c
- cmd/grap/misc.c
- cmd/grap/mkfile
- cmd/grap/plot.c
- cmd/grap/print.c
- cmd/grap/ticks.c
> Adding grap from Harvey due to dependencies

- lib/ap/plan9/__sys_read.c
- lib/ap/plan9/__sys_write.c
> Fixing read write calls

- .travis.yml
Signed-off-by: Sevki <s@sevki.org>
> ci: update clang and gcc versions

- linux.inc
- rc/bin/ld
- removing conflicting old ld wr…apper
> Making possible to choose compiler

- .travis.yml
> Updating travis.yml

- .travis.yml
> Adjusting compilers
